#!/bin/bash
# Check VMESS User Login Script

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Check root
if [ "${EUID}" -ne 0 ]; then
    echo -e "${RED}Please run as root${NC}"
    exit 1
fi

clear
echo -e "${BLUE}=============================${NC}"
echo -e "${YELLOW}     VMESS USER LOGIN     ${NC}"
echo -e "${BLUE}=============================${NC}"
echo -e ""

echo -e "User          Logged IP       Last Login"
echo -e "${BLUE}=============================${NC}"

data=( `cat /etc/xray/config.json | grep '^###' | cut -d ' ' -f 2 | sort | uniq`);

for akun in "${data[@]}"
do
    if [[ -z "$akun" ]]; then
        akun="No username"
    fi
    
    log=$(grep -w "$akun" /var/log/xray/access.log | tail -n 1)
    if [[ -z "$log" ]]; then
        login="No login"
        ip="No IP"
    else
        login=$(echo $log | cut -d " " -f 3 | cut -d ":" -f 1)
        ip=$(echo $log | awk '{print $2}')
    fi
    
    printf "%-13s %-15s %s\n" "$akun" "$ip" "$login"
done

echo -e "${BLUE}=============================${NC}"
echo -e "Total Users: ${#data[@]}" 