#!/bin/bash
# Menu Installation Script

# Create required directories
mkdir -p /usr/local/sbin

# List of menu commands
commands=(
    "add-ssh"
    "trial-ssh"
    "renew-ssh"
    "del-expired"
    "add-xray"
    "del-xray"
    "renew-xray"
    "add-trojan"
    "del-trojan"
    "renew-trojan"
    "del-ssh"
    "check-ssh"
    "monitor-ssh"
    "trial-xray"
    "check-xray"
    "monitor-xray"
    "trial-trojan"
    "check-trojan"
    "monitor-trojan"
    "add-domain"
    "dns-setting"
    "auto-reboot"
    "ram-usage"
    "speedtest"
    "change-port"
    "autobackup"
    "backup"
    "restore"
    "webmin"
    "add-cf"
    "cf-addon"
    "point-domain"
    "timezone"
    "update"
    "bbr"
    "tcp-tweak"
    "restart-services"
    "system-info"
)

# Download and install each command
for cmd in "${commands[@]}"; do
    echo "Installing $cmd..."
    wget -q -O /usr/local/sbin/$cmd "https://raw.githubusercontent.com/Abdofaiz/faiz-vpn/main/menu/$cmd"
    chmod +x /usr/local/sbin/$cmd
done

# Update PATH
echo 'PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"' > /etc/environment
source /etc/environment

echo "Menu installation completed!" 