#!/bin/bash
# Active Login Monitor Script

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Check root
if [ "${EUID}" -ne 0 ]; then
    echo -e "${RED}Please run as root${NC}"
    exit 1
fi

clear
echo -e "${BLUE}=============================${NC}"
echo -e "${YELLOW}     ACTIVE LOGIN MONITOR     ${NC}"
echo -e "${BLUE}=============================${NC}"
echo -e ""

echo -e "SSH & OpenVPN Login:"
echo -e "${BLUE}=============================${NC}"
data=( `ps aux | grep -i dropbear | awk '{print $2}'`);
for PID in "${data[@]}"
do
    NUM=`cat /var/log/auth.log | grep -i dropbear | grep -i "Password auth succeeded" | grep "dropbear\[$PID\]" | wc -l`;
    USER=`cat /var/log/auth.log | grep -i dropbear | grep -i "Password auth succeeded" | grep "dropbear\[$PID\]" | awk '{print $10}'`;
    IP=`cat /var/log/auth.log | grep -i dropbear | grep -i "Password auth succeeded" | grep "dropbear\[$PID\]" | awk '{print $12}'`;
    if [ $NUM -eq 1 ]; then
        echo -e "$USER - $IP";
    fi
done

echo -e "\nXRAY Login:"
echo -e "${BLUE}=============================${NC}"
data=( `cat /etc/xray/config.json | grep '^###' | cut -d ' ' -f 2 | sort | uniq`);
for user in "${data[@]}"
do
    if [[ -z "$user" ]]; then continue; fi
    
    log=$(grep -w "$user" /var/log/xray/access.log | tail -n 1)
    if [[ ! -z "$log" ]]; then
        ip=$(echo $log | awk '{print $2}')
        time=$(echo $log | awk '{print $1}' | cut -d. -f1)
        echo -e "$user - $ip ($time)"
    fi
done

echo -e "${BLUE}=============================${NC}" 