#!/bin/bash
# List Trojan Members Script

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Check root
if [ "${EUID}" -ne 0 ]; then
    echo -e "${RED}Please run as root${NC}"
    exit 1
fi

clear
echo -e "${BLUE}=============================${NC}"
echo -e "${YELLOW}     TROJAN MEMBER LIST     ${NC}"
echo -e "${BLUE}=============================${NC}"
echo -e ""

echo -e "USERNAME          EXPIRED DATE"
echo -e "${BLUE}=============================${NC}"

data=( `cat /etc/xray/config.json | grep '^###' | cut -d ' ' -f 2-3 | grep -v "#trojan" | sort | uniq`);

for user in "${data[@]}"
do
    username=$(echo $user | cut -d ' ' -f 1)
    exp=$(echo $user | cut -d ' ' -f 2)
    
    printf "%-17s %2s\n" "$username" "$exp"
done

echo -e "${BLUE}=============================${NC}"
echo -e "Total Members: ${#data[@]}" 